---
title: "Twitter"
author: "Caroline Li, Jocelyn Hu, Natalie Labossier"
date: "April 24, 2019"
output: pdf_document
---
```{r}
library(dplyr)
library(mosaic)
library(ggplot2)
library(readr)
library(tidyr)
library(tidyverse)
```

```{r}
df<-read.csv("data_twitter - Sheet2.CSV")
```

```{r}
day <- c("Wed","Wed","Thurs","Thurs","Fri","Fri","Wed","Wed","Thurs","Thurs","Fri","Fri","Wed","Wed","Thurs","Thurs","Fri","Fri")
week <- c(rep("1", 6),                                  rep("2",6), rep("3",6))
df<-cbind(day,df)
df<-cbind(week,df)

```

```{r sum_engage}
df<-df%>%
  mutate(sum_engage=likes_48+retweets_48+comments_48)%>%
  unite(cell, time, type,remove=FALSE)

```
```{r}

glimpse(df)
summary(df)
```

#Informal Analysis

##side by side boxplot

```{r}
#looking at variability by condition
ggplot(df, aes(x = type, fill = time, y = sum_engage)) +
  geom_boxplot()

```

##Parallel dot graph

```{r}
#looking at variability by condition
ggplot(df, aes(x = type, color = time, y = sum_engage)) +
    geom_jitter(height = 0.10, width = 0.05, alpha = .7)
```

##Interaction effects

```{r}
ggplot(df, aes(x = type, 
                    y = sum_engage, 
                    color = time,
                    group = time)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", se = 0)
```


```{r}
ggplot(df, aes(x = time, 
                    y = sum_engage, 
                    color = type,
                    group = type)) +
  geom_point(size = 2) +
  geom_smooth(method = "lm", se = 0)
```


# Assembly Line Metaphor

## Assembly Line Instructions

To make the set of assembly instructions, first we calculate the effects of all of our structural factors under the Fisher assumptions. We use the data to calculate all of these effects.
```{r}
df<-df%>%
  filter(type =="informative"| type =="inspirational")
```

```{r}
df <- df%>%
  mutate(benchmark = mean(sum_engage)) #universal factor
```

```{r}
df <- df %>%
  group_by(type) %>%
  mutate(type_mean = mean(sum_engage),
         type_effect = type_mean - benchmark) 
#for each level of type factor
```

```{r}
df <- df %>%
  group_by(week) %>%
  mutate(week_mean = mean(sum_engage),
         week_effect = week_mean - benchmark) 
#for each level of type factor
```

```{r}
df <- df %>%
  group_by(day) %>%
  mutate(day_mean = mean(sum_engage),
         day_effect = day_mean - benchmark) 
#for each level of type factor
```

```{r}
df <- df %>%
  group_by(time) %>%
  mutate(time_mean = mean(sum_engage),
         time_effect = time_mean - benchmark) 
#for each level of type factor
```

```{r}
df <- df %>%
  group_by(cell) %>%
  mutate(cell_mean = mean(sum_engage),
         interaction_effect = cell_mean - (type_mean + time_mean - benchmark)) #for each cell of interaction
```

```{r}
df<- df %>%
  ungroup() %>%
  mutate(residuals = sum_engage - (benchmark 
                             + type_effect 
                             + time_effect 
                             + interaction_effect
                             + day_effect
                             + week_effect))%>% #universal factor
  select(-type_mean, -time_mean, 
         -cell_mean, -day_mean, -week_mean) #removing the stuff we don't need
  
```

```{r}
df2<-df%>%
  filter(type =="informative"| type =="inspirational")
```

#ANOVA

```{r}
twitter <- aov(sum_engage ~ type+time+day+week+type*time, data = df2)

anova1<-anova(twitter)
summary(twitter)

#favstats(sum_engage~type|time, data = df2)

# library(mosaic)
# tally(~time|as.character(type), data = df2)
# 
# df2$type
```



```{r}
is.num <- sapply(anova1, is.numeric)
anova1[is.num] <- lapply(anova1[is.num], round, 3)
anova1[4,5]<-"0.250"
anova1[1,5]<-"0.230"
anova1[1,6]<-""
anova1[2,6]<-"*"
anova1[3,6]<-"*"
anova1[4,6]<-" "
anova1[5,6]<-" "
anova1[6,6]<-" "
anova1[6,5]<-" "
anova1[6,4]<-" "
anova2<-anova1[1:6,]

```

```{r}
library(kableExtra)
kable(anova2, digits = 3, format = "latex", booktabs = T,col.names = c("Df","Sum Sq","Mean Sq","F value"," Pr(>F)"," "))%>%
  kable_styling(full_width = F, font_size = 12)%>%add_footnote("Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1", notation="alphabet")%>%column_spec(1, width = "5em") 
```



#summary statistics



```{r}
library(tidyverse)
df2<-as.data.frame(df)%>%
  na.omit()%>%
  select(sum_engage,likes_48,retweets_48,comments_48,type)
```

```{r}
library(stargazer)
stargazer(data = df2, type = "html", title="Summary statistics of DV", digits=2, out="tablesum.html",covariate.labels = c("Total Engagement","#Likes","#Retweets","#Comments","type"))

```
